services:
  ms-agosto-03:
    container_name: ms-agosto-03-python
    image: omarleon/ms-agosto-03:v1
    ports:
      - "8008:8008"
    command: uvicorn main:app --host 0.0.0.0 --port 8008
    restart: unless-stopped